version : '3'

services :
    backend :
        image : pyoa-node:latest
        container_name : pyoa_backend
        working_dir : /app
        networks :
            - pyoa-network
        ports :
            - "3000:3000"
        command : node index.js
        links :
            - mongodb
        depends_on :
            - mongodb


    mongodb :
        image : mongo:latest
        container_name : mongodb
        restart : always
        environment :
            MONGO_INITDB_DATABASE: pyoa
        ports :
            - "27017:27017"
        volumes :
            - "./mongo-scripts/artefacts.js:/docker-entrypoint-initdb.d/artefacts.js"
            - "./mongo-scripts/ressources.js:/docker-entrypoint-initdb.d/ressources.js"
            - "./mongo-scripts/creatures.js:/docker-entrypoint-initdb.d/creatures.js"
            - "./mongo-scripts/users.js:/docker-entrypoint-initdb.d/users.js"
            #- "db_pyoa:/data/db"
        networks :
            - pyoa-network

# -> Sauvegarde des datas
#volumes :
#    db_pyoa:

networks :
    pyoa-network:
