db.ressources.save({"name" : "Paper" , "description" : "But... whyt ???","rarity" : "Very Very Common","ratioTU" : 25})
db.ressources.save({"name" : "Wood" , "description" : "Just some wookd","rarity" : "Very Common","ratioTU" : 10})
db.ressources.save({"name" : "Mud" , "description" : "Some disgusting mud... gross","rarity" : "Very Common","ratioTU" : 7})
db.ressources.save({"name" : "Rock" , "description" : "But Metal is better you know that ?","rarity" : "Very Common","ratioTU" : 4.5})
db.ressources.save({"name" : "Minimal Gem" , "description" : "A tinny gem. Will be always usefull to summon creatures.","rarity" : "Uncommon","ratioTU" : 1})
db.ressources.save({"name" : "Medium Gem" , "description" : "A medium gem. Usefull to summon medium level creatures.","rarity" : "Rare","ratioTU" : 0.3})
db.ressources.save({"name" : "Large Gem" , "description" : "A rare gem for rare creatures.","rarity" : "Very Rare","ratioTU" : 0.025})
db.ressources.save({"name" : "Tissue" , "description" : "Some creatures are pretty and like have nice clothes :","rarity" : "Uncommon","ratioTU" : 0.7})
db.ressources.save({"name" : "Strange Material" , "description" : "Nobody know what is it... weird.","rarity" : "Very Rare","ratioTU" : 0.0005})
db.ressources.save({"name" : "Bamboo" , "description" : "No, this isn\'t the same thing than the wood !","rarity" : "Rare","ratioTU" : 0.25})
db.ressources.save({"name" : "Fire Essence" , "description" : "This special gem contains a piece of an etnernal fire.","rarity" : "Rare","ratioTU" : 0.15})
db.ressources.save({"name" : "Water Essence" , "description" : "This special gem contains an extract of a mysterious water.","rarity" : "Rare","ratioTU" : 0.15})
db.ressources.save({"name" : "Wind Essence" , "description" : "This special gem contains a fresh breeze from a pure wind.","rarity" : "Rare","ratioTU" : 0.15})
db.ressources.save({"name" : "Metal" , "description" : "Better than rock !","rarity" : "Uncommon","ratioTU" : 0.2})
db.ressources.save({"name" : "Fragment of the Forgetten Relic" , "description" : "A legend says that if you find all the fragments a legendary creature will be summon.","rarity" : "Very Rare","ratioTU" : 0.0025})
